export const THEMES = [
    'advexcel',
    'airplane',
    'corplan',
    'corplanold',
    'dark',
    'dev',
    'domrf',
    'fixprice',
    'magnit',
    'olapsoft',
    'optimacros',
    'orange',
    'ovk',
    'rublevoarch',
    'sobi',
    'stada',
    'tinkoff',
    'tvel',
    'unilever',
    'yadrolight',
    'yadromain',
].map((value) => ({ value, label: value }));
