
export default function CombinationChartIcon({ fill = 'black', opacity = 1 }) {
    return (
        <svg
            fill="none"
            height="15"
            style={{ opacity }}
            viewBox="0 0 48 48"
            width="15"
            xmlns="http://www.w3.org/2000/svg"
        >
            <g clipPath="url(#clip0_28_136)">
                <rect
                    fill={fill}
                    height="14.7692"
                    width="7.38462"
                    x="1"
                    y="33.231"
                />
                <rect
                    fill={fill}
                    height="18.4615"
                    width="7.38462"
                    x="10.8461"
                    y="29.5386"
                />
                <rect
                    fill={fill}
                    height="25.8462"
                    width="7.38462"
                    x="20.6923"
                    y="22.1538"
                />
                <rect
                    fill={fill}
                    height="34.4615"
                    width="7.38462"
                    x="40.3846"
                    y="13.5386"
                />
                <rect
                    fill={fill}
                    height="20.9231"
                    width="7.38462"
                    x="30.5385"
                    y="27.0771"
                />
                <rect
                    fill={fill}
                    height="3"
                    rx="1.5"
                    width="3"
                    x="2.23077"
                    y="20.9229"
                />
                <rect
                    fill={fill}
                    height="3"
                    rx="1.5"
                    width="3"
                    x="12.077"
                    y="16"
                />
                <rect
                    fill={fill}
                    height="3"
                    rx="1.5"
                    width="3"
                    x="21.923"
                    y="8.61572"
                />
                <rect
                    fill={fill}
                    height="3"
                    rx="1.5"
                    width="3"
                    x="32"
                    y="13"
                />
                <rect
                    fill={fill}
                    height="3"
                    rx="1.5"
                    width="3"
                    x="42"
                    y="4"
                />
                <rect
                    fill={fill}
                    height="1.23077"
                    transform="rotate(-25.8261 4.5379 21.3398)"
                    width="8.60997"
                    x="4.5379"
                    y="21.3398"
                />
                <rect
                    fill={fill}
                    height="1.23077"
                    transform="rotate(-35.7299 14.1597 16.1597)"
                    width="10.5779"
                    x="14.1597"
                    y="16.1597"
                />
                <rect
                    fill={fill}
                    height="1.23077"
                    transform="rotate(24.8424 24.6981 10.084)"
                    width="8.72869"
                    x="24.6981"
                    y="10.084"
                />
                <rect
                    fill={fill}
                    height="1.23077"
                    transform="rotate(-43.8186 33.9656 13.6963)"
                    width="13.0475"
                    x="33.9656"
                    y="13.6963"
                />
            </g>
            <defs>
                <clipPath id="clip0_28_136">
                    <rect
                        fill="white"
                        height="48"
                        width="48"
                    />
                </clipPath>
            </defs>
        </svg>
    )
}
