export const foldersList = [
    {
        entityLongId: 118000000001,
        name: '1. Основные модели PD',
        parentEntityLongId: -1,
        renaming: false,
        deleting: false,
        countDataBases: 0,
        isPublic: true,
        ownerLongId: -1,
        allNestedModelsCount: 6,
    },
    {
        entityLongId: 118000000002,
        name: 'Folder name 1',
        parentEntityLongId: -1,
        renaming: false,
        deleting: false,
        countDataBases: 0,
        isPublic: true,
        ownerLongId: 111000000162,
        allNestedModelsCount: 0,
    },
    {
        entityLongId: 118000000003,
        name: '2. Product QA',
        parentEntityLongId: -1,
        renaming: false,
        deleting: false,
        countDataBases: 0,
        isPublic: true,
        ownerLongId: -1,
        allNestedModelsCount: 15,
    },
    {
        entityLongId: 118000000004,
        name: 'Folder name 3',
        parentEntityLongId: -1,
        renaming: false,
        deleting: false,
        countDataBases: 0,
        isPublic: true,
        ownerLongId: 111000000459,
        allNestedModelsCount: 2,
    },
    {
        entityLongId: 118000000005,
        name: 'Folder name 5',
        parentEntityLongId: -1,
        renaming: false,
        deleting: false,
        countDataBases: 0,
        isPublic: true,
        ownerLongId: 111000000162,
        allNestedModelsCount: 0,
    },
    {
        entityLongId: 118000000006,
        name: 'Folder name 11123',
        parentEntityLongId: -1,
        renaming: false,
        deleting: false,
        countDataBases: 0,
        isPublic: true,
        ownerLongId: -1,
        allNestedModelsCount: 1,
    },
];
