export const menuTags = [
    {
        longId: 0,
        name: 'All',
    },
    {
        longId: 138000000199,
        name: 'Favorites',
        color: '#212121',
        useInFilters: true,
        isPersonal: true,
        icon: 'account_circle',
    },
    {
        longId: 138000000021,
        name: 'Не удалять!',
        color: '#f23326',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
    {
        longId: 138000000031,
        name: 'Test',
        color: '#0515f4',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
    {
        longId: 138000000029,
        name: 'Documentation',
        color: '#0cbb01',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
    {
        longId: 138000000027,
        name: 'Examples',
        color: '#09f0e4',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
    {
        longId: 138000000189,
        name: 'Production',
        color: '#ed8e09',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
    {
        longId: 138000000173,
        name: 'для App Store или Stand!',
        color: '#da0ff2',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
    {
        longId: 138000000111,
        name: 'debug для BE',
        color: '#f10a0a',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
    {
        longId: 138000000022,
        name: 'BDD',
        color: '#a7b301',
        useInFilters: true,
        isPersonal: false,
        icon: null,
    },
];
