import { defineConfig } from 'tsup';
import path from 'path';
import conf from '../../tsup.config';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const output = path.resolve(
    __dirname,
    '../../../om_ws_fe/node_modules/@optimacros-ui/kit-internal/dist',
);

export default defineConfig({
    ...conf,
    outDir: output,
    dts: false,
    publicDir: path.resolve(__dirname, '../themes/src/assets'),
    minify: false,
    minifyIdentifiers: false,
});
// "@optimacros-ui/badge": "^2.0.9",
// "@optimacros-ui/button": "^2.0.9",
// "@optimacros-ui/button-group": "^2.0.9",
// "@optimacros-ui/calendar": "^2.0.9",
// "@optimacros-ui/checkbox": "^2.0.9",
// "@optimacros-ui/chip": "^2.0.9",
// "@optimacros-ui/collapsible": "^2.0.9",
// "@optimacros-ui/color-picker": "^2.0.9",
// "@optimacros-ui/counter": "^2.0.9",
// "@optimacros-ui/divider": "^2.0.9",
// "@optimacros-ui/draggable": "^2.0.9",
// "@optimacros-ui/editable": "^2.0.9",
// "@optimacros-ui/favourite": "^2.0.9",
// "@optimacros-ui/field": "^2.0.9",
// "@optimacros-ui/file-upload": "^2.0.9",
// "@optimacros-ui/flex": "^2.0.9",
// "@optimacros-ui/font-icon": "^2.0.9",
// "@optimacros-ui/footer": "^2.0.9",
// "@optimacros-ui/grid": "^2.0.9",
// "@optimacros-ui/header": "^2.0.9",
// "@optimacros-ui/icon": "^2.0.9",
// "@optimacros-ui/icon-button": "^2.0.9",
// "@optimacros-ui/image": "^2.0.9",
// "@optimacros-ui/loader": "^2.0.9",
// "@optimacros-ui/markdown-editor": "^2.0.9",
// "@optimacros-ui/memory-counter": "^2.0.9",
// "@optimacros-ui/menu": "^2.0.9",
// "@optimacros-ui/modal": "^2.0.9",
// "@optimacros-ui/navigation": "^2.0.9",
// "@optimacros-ui/popover": "^2.0.9",
// "@optimacros-ui/radio-group": "^2.0.9",
// "@optimacros-ui/resizable": "^2.0.9",
// "@optimacros-ui/segmented-control": "^2.0.9",
// "@optimacros-ui/select": "^2.0.9",
// "@optimacros-ui/sidebar": "^2.0.9",
// "@optimacros-ui/slider": "^2.0.9",
// "@optimacros-ui/spacer": "^2.0.9",
// "@optimacros-ui/stack": "^2.0.9",
// "@optimacros-ui/store": "^2.0.9",
// "@optimacros-ui/switch": "^2.0.9",
// "@optimacros-ui/tabs": "^2.0.9",
// "@optimacros-ui/text": "^2.0.9",
// "@optimacros-ui/themes": "^2.0.9",
// "@optimacros-ui/toast": "^2.0.9",
// "@optimacros-ui/toggle": "^2.0.9",
// "@optimacros-ui/toolbar": "^2.0.9",
// "@optimacros-ui/tooltip": "^2.0.9",
// "@optimacros-ui/tree-menu": "^2.0.9",
// "@optimacros-ui/tree-view": "^2.0.9",
// "@optimacros-ui/types": "^2.0.9",
// "@optimacros-ui/utils": "^2.0.9",
// "@optimacros-ui/virtual": "^2.0.9",
// "@optimacros-ui/visually-hidden": "^2.0.9",
