// @ts-nocheck
export const KEY_CODES = {
    SPACE: 32,
    ESC: 27,
    ENTER: 13,
    ARROW_LEFT: 37,
    ARROW_UP: 38,
    ARROW_RIGHT: 39,
    ARROW_DOWN: 40,
};

export const KEYBOARD_KEYS = {
    ENTER: 'Enter',
};

export const BASE_MENU_ELEMENT_HEIGHT = 25;
export const BASE_MENU_ELEMENT_HEIGHT_ZOOM_0 = 22;
export const BASE_MENU_ELEMENT_HEIGHT_ZOOM_1 = 23;
export const BASE_MENU_ELEMENT_HEIGHT_ZOOM_2 = 24;
export const BASE_MENU_ELEMENT_HEIGHT_ZOOM_3 = 25;
export const BASE_MENU_ELEMENT_PADDING_BOTTOM = 6;
export const BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_0 = 2;
export const BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_1 = 3;
export const BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_2 = 4;
export const BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_3 = 6;
export const BASE_MENU_PADDING_LEFT_ELEMENT = 28;
export const BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_0 = 15;
export const BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_1 = 19;
export const BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_2 = 23;
export const BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_3 = 28;
export const BASE_MENU_COUNT_ELEMENTS = 30;
export const BASE_MENU_COUNT_ELEMENTS_ZOOM_0 = 38;
export const BASE_MENU_COUNT_ELEMENTS_ZOOM_1 = 35;
export const BASE_MENU_COUNT_ELEMENTS_ZOOM_2 = 33;
export const BASE_MENU_COUNT_ELEMENTS_ZOOM_3 = 30;
export const BASE_MENU_STATIC_OFFSET_ELEMENT = 12;

export const constants = {
    KEY_CODES,
    BASE_MENU_ELEMENT_HEIGHT,
    BASE_MENU_ELEMENT_HEIGHT_ZOOM_0,
    BASE_MENU_ELEMENT_HEIGHT_ZOOM_1,
    BASE_MENU_ELEMENT_HEIGHT_ZOOM_2,
    BASE_MENU_ELEMENT_HEIGHT_ZOOM_3,
    BASE_MENU_ELEMENT_PADDING_BOTTOM,
    BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_0,
    BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_1,
    BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_2,
    BASE_MENU_ELEMENT_PADDING_BOTTOM_ZOOM_3,
    BASE_MENU_PADDING_LEFT_ELEMENT,
    BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_0,
    BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_1,
    BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_2,
    BASE_MENU_PADDING_LEFT_ELEMENT_ZOOM_3,
    BASE_MENU_COUNT_ELEMENTS,
    BASE_MENU_COUNT_ELEMENTS_ZOOM_0,
    BASE_MENU_COUNT_ELEMENTS_ZOOM_1,
    BASE_MENU_COUNT_ELEMENTS_ZOOM_2,
    BASE_MENU_COUNT_ELEMENTS_ZOOM_3,
    BASE_MENU_STATIC_OFFSET_ELEMENT,
};

export const getConstant = (key) => constants[key];

export default constants;
