export const modelsList = [
    {
        id: '8f667dasdasdasd57e9755ae6',
        name: 'Unnamed Model - 20231227164445224',
        source: [],
        summary: {
            modelName: 'Unnamed Model - 20231227164445224',
            cellCount: 0,
            memory: 17091788,
            modelId: '8f667dasdasdasd57e9755ae6',
            viewedAt: 1705954474,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1705562406,
            createdAt: 1703684711,
            updatedAt: 1703684711,
            isOffline: false,
            serial: 0,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: '22.01.2024, 23:14',
        dateCreate: '27.12.2023, 16:45',
        dateUpdate: '27.12.2023, 16:45',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: false,
        isPrivate: false,
    },
    {
        id: '176c44asdfasdfasdf94b',
        name: 'Test-model-v1',
        source: [],
        summary: {
            modelName: 'Test-model-v1',
            cellCount: 0,
            memory: 0,
            modelId: '176c44asdfasdfasdf94b',
            viewedAt: 1685004688,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1689120075,
            createdAt: 1684734308,
            updatedAt: 1687436576,
            isOffline: true,
            serial: 4,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: '25.05.2023, 11:51',
        dateCreate: '22.05.2023, 08:45',
        dateUpdate: '22.06.2023, 15:22',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: true,
        isPrivate: false,
    },
    {
        id: '0a71ad1asdfsdfsdagasg55f9bf0',
        name: 'test-topic-12782',
        source: [],
        summary: {
            modelName: 'test-topic-12782',
            cellCount: 0,
            memory: 0,
            modelId: '0a71ad1asdfsdfsdagasg55f9bf0',
            viewedAt: 1656440324,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1659908836,
            createdAt: 1656439748,
            updatedAt: 1656581890,
            isOffline: true,
            serial: 154,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: '28.06.2022, 21:18',
        dateCreate: '28.06.2022, 21:09',
        dateUpdate: '30.06.2022, 12:38',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: true,
        isPrivate: false,
    },
    {
        id: '6beeasdfsdgdgd13bfe709515b',
        name: 'Test 1.1 Нестрогая формула #91',
        source: [],
        summary: {
            modelName: 'Test 1.1 Нестрогая формула #91',
            cellCount: 0,
            memory: 0,
            modelId: '6beeasdfsdgdgd13bfe709515b',
            viewedAt: 1654698253,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1654698199,
            createdAt: 1637656034,
            updatedAt: 1654698252,
            isOffline: true,
            serial: 12,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: '08.06.2022, 17:24',
        dateCreate: '23.11.2021, 11:27',
        dateUpdate: '08.06.2022, 17:24',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: true,
        isPrivate: false,
    },
    {
        id: '40f7asdggsdgavsdvvcxzc05c4e8ea',
        name: 'model_drill_down_sum_test',
        source: [],
        summary: {
            modelName: 'model_drill_down_sum_test',
            cellCount: 0,
            memory: 0,
            modelId: '40f7asdggsdgavsdvvcxzc05c4e8ea',
            viewedAt: 1646212945,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1676003495,
            createdAt: 1646128603,
            updatedAt: 1674828716,
            isOffline: true,
            serial: 113,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: '02.03.2022, 12:22',
        dateCreate: '01.03.2022, 12:56',
        dateUpdate: '27.01.2023, 17:11',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: true,
        isPrivate: false,
    },
    {
        id: '09539f9fd3zxcgcgxgz92f5ed95',
        name: 'Switchover',
        source: [],
        summary: {
            modelName: 'Switchover',
            cellCount: 0,
            memory: 0,
            modelId: '09539f9fd3zxcgcgxgz92f5ed95',
            viewedAt: 1638214789,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1643681041,
            createdAt: 1624258113,
            updatedAt: 1638788967,
            isOffline: true,
            serial: 48,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: '29.11.2021, 22:39',
        dateCreate: '21.06.2021, 09:48',
        dateUpdate: '06.12.2021, 14:09',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: true,
        isPrivate: false,
    },
    {
        id: 'd7azxcgdfgsdga1746c25',
        name: 'E2E Flexible Grid Model 1 3',
        source: [],
        summary: {
            modelName: 'E2E Flexible Grid Model 1 3',
            cellCount: 0,
            memory: 32715571,
            modelId: 'd7azxcgdfgsdga1746c25',
            viewedAt: null,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1705945865,
            createdAt: 1705945811,
            updatedAt: 1705945811,
            isOffline: false,
            serial: 0,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: null,
        dateCreate: '22.01.2024, 20:50',
        dateUpdate: '22.01.2024, 20:50',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: false,
        isPrivate: false,
    },
    {
        id: 'cfe963vasvafbfbafb6dc946',
        name: 'E2E Context to Dimension 15 #102307',
        source: [],
        summary: {
            modelName: 'E2E Context to Dimension 15 #102307',
            cellCount: 0,
            memory: 54735667,
            modelId: 'cfe963vasvafbfbafb6dc946',
            viewedAt: null,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1705571943,
            createdAt: 1705571884,
            updatedAt: 1705571884,
            isOffline: false,
            serial: 0,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: null,
        dateCreate: '18.01.2024, 12:58',
        dateUpdate: '18.01.2024, 12:58',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: false,
        isPrivate: false,
    },
    {
        id: '300dbasfbafbadfbafd159df82',
        name: 'E2E SPD',
        source: [],
        summary: {
            modelName: 'E2E SPD',
            cellCount: 0,
            memory: 147456,
            modelId: '300dbasfbafbadfbafd159df82',
            viewedAt: null,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1705561369,
            createdAt: 1705410992,
            updatedAt: 1705410992,
            isOffline: false,
            serial: 0,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: null,
        dateCreate: '16.01.2024, 16:16',
        dateUpdate: '16.01.2024, 16:16',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: false,
        isPrivate: false,
    },
    {
        id: 'b413dabsfdadfbadfadfb62',
        name: 'COPY - for tests - 20240116155216786',
        source: [],
        summary: {
            modelName: 'COPY - for tests - 20240116155216786',
            cellCount: 0,
            memory: 211288064,
            modelId: 'b413dabsfdadfbadfadfb62',
            viewedAt: null,
            tagLongIds: [],
            workspaceFolderLongId: -1,
            autoCalc: true,
            lastSyncDate: 1705561437,
            createdAt: 1705409539,
            updatedAt: 1705409539,
            isOffline: false,
            serial: 0,
            isMultiThreadedStorageCommunication: true,
            storageVersion: 'v7.17-2-g343f90b8e',
            storageBuildExecutable: 'cxp_server',
            isSetStorageProfiler: false,
            isPrivate: false,
            owner: null,
            storageReadMode: 'CONSISTENT_READ',
            storageWriteMode: 'CONSISTENT_WRITE',
        },
        location: 'DEMO',
        date: null,
        dateCreate: '16.01.2024, 15:52',
        dateUpdate: '16.01.2024, 15:52',
        renaming: false,
        current: false,
        tagsIds: [],
        parentFolder: -1,
        isOffline: false,
        isPrivate: false,
    },
];
